filebeat.inputs:
  - type: filestream
    id: event-service-file
    enabled: true
    paths:
      - /var/log/event-service/event-service.log
      - /var/log/event-service/event-service-*.log
    start_position: beginning
    ignore_older: 0
    fields:
      application: event-service
    file_identity:
      native: ~
    # Important: Add these for better file monitoring
    prospector:
      scanner:
        check_interval: 1s  # Check for file changes every second
    close_inactive: 5m
    close_on_state_change:
      inactive: true
    clean_inactive: 0
    harvester_buffer_size: 16384
    max_bytes: 10485760
    # Force Filebeat to check file changes
    resend_on_touch: true
    
output.logstash:
  hosts: ["logstash:5044"]
  ssl.enabled: false

logging.level: info  # Change back from debug